lorawan_public = false
clksrc = 1

[[radios]]
id = 0
type = 'SX1257'
freq = 867_500_000
rssi_offset = -166.0
tx_enable = false

[[radios]]
id = 1
type = 'SX1257'
freq = 868_500_000
rssi_offset = -166.0
tx_enable = false

[[multirate_channels]]
id = 0
radio = 1
if = -400_000

[[multirate_channels]]
id = 1
radio =  1
if = -200_000

[[multirate_channels]]
id = 2
radio = 1
if = 0

[[multirate_channels]]
id = 3
radio = 0
if = -400_000

[[multirate_channels]]
id = 4
radio = 0
if = -200_000

[[multirate_channels]]
id = 5
radio = 0
if = 0

[[multirate_channels]]
id = 6
radio = 0
if = 200_000

[[multirate_channels]]
id = 7
radio = 0
if = 400_000
