[board]
lorawan_public = false
clksrc = 1

[[radios]]
id = 0
type = 'SX1257'
freq = 911_500_000
rssi_offset = -166.0
tx_enable = true

[[radios]]
id = 1
type = 'SX1257'
freq = 903_500_000
rssi_offset = -166.0
tx_enable = false

[[multirate_channels]]
radio = 1
if = -400_000

[[multirate_channels]]
radio =  1
if = -200_000

[[multirate_channels]]
radio = 1
if = 0

[[multirate_channels]]
radio = 0
if = -400_000

[[multirate_channels]]
radio = 0
if = -200_000

[[multirate_channels]]
radio = 0
if = 0

[[multirate_channels]]
radio = 0
if = 200_000

[[multirate_channels]]
radio = 0
if = 400_000
