[package]
name = "longfi-hotspot"
version = "0.1.0"
edition = "2018"
authors = ["Louis Thiery <louis@helium.com>"]

[dependencies]
lfc = {path = "../lfc"}
messages = { path = "../messages" }
mio             = "0.6"
protobuf = "2.5.0"
rand = "0.3"
log = "0.4.6"

[dev-dependencies]
lazy_static = "*"
