[package]
name = "loragw_test_client"
version = "0.1.0"
authors = ["Jay Kickliter <jay@kickliter.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3.1"
env_logger = "0.6.1"
loragw = { path = "../loragw" }
