[package]
name = "concentrate"
version = "0.1.0"
authors = ["Jay Kickliter <jay@kickliter.com>"]
edition = "2018"

[dependencies]
env_logger = "0.6.1"
log = "0.4.6"
loragw = { path = "../loragw" }
messages = { path = "../messages" }
protobuf = "2.6.0"
quick-error = "1.2.2"
structopt = "0.2.15"
