[package]
name = "loragw"
version = "0.2.0"
edition = "2018"
authors = ["Jay Kickliter <jay@kickliter.com>"]

[dependencies]
llg = { package = "libloragw-sx1301-sys", path = "../libloragw-sx1301-sys" }
log = "0.4.6"
quick-error = "1.2.2"

[dev-dependencies]
lazy_static = "*"
