[package]
name = "loragw"
version = "0.1.2"
authors = ["Jay Kickliter <jay@kickliter.com>"]

[dependencies]
libloragw-sys = { path = "../libloragw-sys" }
log = "0.4.6"
quick-error = "1.2.2"

[dev-dependencies]
lazy_static = "*"
